import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
import NavBar from '@/components/navBar/navBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        {/* @ts-expect-error Server Component */}
        <NavBar />
        <div className='content-container-flexbox w-full flex flex-row justify-center'>
          <div className='spacer flex-grow w-0'></div>
          <div className="content-container flex-initial w-[48rem] h-full">
            {props.children}
          </div>
          <div className='spacer flex-grow w-0'></div>
        </div>
      </body>
    </html>
  )
}
